config/routes.rb
Rails.application.routes.draw do
  root 'static#Home'

  devise_for :users

  resources :users do
    resources :workouts
  end

  resources :workouts do
    resources :lifts
  end

  resources :exercises
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_many :muscle_exercises
  has_many :muscles, through: :muscle_exercises

end

app/models/lift.rb
class Lift < ApplicationRecord

  belongs_to :workout

end

app/models/muscle.rb
class Muscle < ApplicationRecord
  has_many :muscle_exercises
  has_many :exercises, through: :muscle_exercises

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :lifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :birthday, :is_male, :email, :password, :remember_me)}
      devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:email, :password, :remember_me)}
      devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :birthday, :is_male, :email, :password, :current_password, :remember_me)}
    end
  private

  def after_sign_in_path_for(resource)
    @user
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name)
  end
end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController

  def create
    @workout = Workout.find(params[:workout_id])
    @lift = @workout.lifts.create(set_params)
    redirect_to @workout
    flash[:success] = "New Set Created"
  end

  private

    def set_params
      params.require(:lift).permit(:exercise, :reps, :weight, :duration)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def Home
  end

  def Wellness
  end

  def Sports_Performance
  end

  def Login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @workouts = @user.workouts.all
  end

  def edit
    @user = User.find(params[:user_id])
    @workouts = @user.workouts.find(params[:id])
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  #TODO Before action, check for user/signed in
  def index
    @user = User.find(params[:user_id])
    @workouts = @user.workouts.all
  end

  def show
    @workout = Workout.find(params[:id])
    @lifts = @workout.lifts
#    @lift = @workout.sets.first
  end

  def new
    @user = User.find(params[:user_id])
    @workout = @user.workouts.build
  end

  def create
    @user = User.find(params[:user_id])
    @workout = @user.workouts.create(workout_params)
    flash[:success] = "New workout created successfully"
    redirect_to user_path(@user)
  end

  def edit
    @user = User.find(params[:user_id])
    @workout = @user.workouts.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @workout = @user.workouts.find(params[:id])
    if @workout.update(workout_params)
      flash[:success] = "Workout was updated successfully!"
      redirect_to user_path(@user)
    else
      flash[:danger] = "#{@workout.errors}"
      redirect_to 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @workout = @user.workouts.find(params[:id]).destroy
    flash[:success] = "Workout deleted successfully"
    redirect_to user_path(@user)
  end

  private

  def workout_params
    params.require(:workout).permit(:date, :name, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/lifts_helper.rb
module LiftsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def full_name
    @user.first_name + " " + @user.last_name
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/index.html.erb
<h1>Exercises#index</h1>
<p>Find me in app/views/exercises/index.html.erb</p>

app/views/exercises/new.html.erb
<h1>Exercises#new</h1>
<p>Find me in app/views/exercises/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>&copy; Sanchez Sykes Company 2018 </p>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to "Website", root_url, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if !current_user %>
            <ul class="nav navbar-nav">
              <li>
                <a href= "#AboutUs"> About Us </a>
              </li>
                <li>
                    <a href= "#SportsPerformance"> Sports Performance </a>
                </li>
                <li>
                    <a href= "#Wellness"> Wellness </a>
                </li>
            </ul>
            <% end %>

            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.first_name + "'s Profile" %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings",edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure?"} %>
                  </li>
                </ul>
              </li>
              <% else %>
              <li>
                <%= link_to "Login", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Register", new_user_registration_path %>
              </li>
              <%end%>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Up 2 Speed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render "layouts/navigation" %>


      <div class="container col-lg-12">
        <!-- Flash messages -->
          <div class="row">
              <div class="col-lg-12 text-center">
                <% flash.each do |a,b| %>
                	<div class="alert alert-success"> <%= b %> </div>
                <% end %>
              </div>
          </div>
          <!-- /.row -->
      <!-- Page Content -->
        <%= yield %>
        <%= render "layouts/footer" %>
      </div>
      <!-- /.container -->
  </body>
  </html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= full_name %>
      </h1>
      <%= link_to "Add a workout", new_user_workout_path(@user) %>


    </section>
  </aside>
  <div class="col-md-4">
    <%= render 'workouts/workouts' %>

  </div>
  <div class="col-md-4">
    <h1>Meals </h1>

  </div>
</div>

app/views/workouts/_form.html.erb
<%= form_for ([@user, @workout]) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => 'Workout name' %><br />
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date %><br />
  </div>
  <%= f.submit "Submit" %>

<% end %>

app/views/workouts/_lifts_form.html.erb
<%= form_for ([@workout, @workout.lifts.build]) do |f| %>

  <div class="field">
    <%= f.label :exercise %>
    <%= f.collection_select( :exercise_id, Exercise.all, :id, :name) %><br />
  </div>

  <div class="field">
    <%= f.label :reps %>
    <%= f.select :reps, (0..50) %><br  />
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight, min: 0, max: 1200, step: 1 %><br />
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.time_field :duration %><br />
  </div>
  <%= f.submit "Submit" %>

<% end %>

app/views/workouts/_sets_form.html.erb
<%= form_for @set do |f| %>

  <div class="field">
    <%= f.label :exercise %>
    <%= f.collection_select( :exercise, Exercise.all, :id, :name) %><br />
  </div>

  <div class="field">
    <%= f.label :reps %>
    <%= f.select :reps, (0..50) %><br  />
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.select :weight, (0..50) %><br />
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.time_field :duration %><br />
  </div>
  <%= f.submit "Submit" %>

<% end %>

app/views/workouts/_workouts.html.erb
<h1>Workouts</h1>

<table>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to "#{workout.name}", user_workout_path(@user, workout) %></td>
        <td><%= link_to 'Edit', edit_user_workout_path(@user, workout) %></td>
        <td><%= link_to 'Destroy', [@user, workout], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/edit.html.erb
<h1>Edit Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.name %></td>
        <td><%= link_to 'Show', user_workout_path(@user, workout) %></td>
        <td><%= link_to 'Edit', edit_user_workout_path(@user, workout) %></td>
        <td><%= link_to 'Destroy', [@user, workout], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', user_path(@user) %>

app/views/workouts/show.html.erb
<h1> <%= @workout.name %>
</p>
<%= @workout.date %>
</h1>

<%= render 'lifts_form', workout: @workout %>